### ISSUE TITLE
Update failed + groups lost

### ISSUE THREAD

**Issue by johnnyb2012** [threethan/LightningLauncher#102]
Q2 update from 6.2 to 6.3 fails.

"Failed to download package!
Please check your internet connection and try again later."

After new installation (probably 6.3) via SideQuest all my goups are lost and import my saved settings works for visual appearance only.
Then I tried 7.0 from Github but it did not help either.

I have over 200 apps/games so it's frustrating to recreate my groups.

**Comment by threethan** [comment]
I am sorry you lost your groups. My best guess is that you did, in fact, update to 7.0.0 from sidequest, and attempted to load an incompatible backup from before 7.0.0. 7.0.1 will no longer show the option to import incompatible backups.

The auto update issue is now resolved, the package was named incorrectly on github so the auto-updater would fail when upgrading from certain versions (6.2.X and 6.3.X). Additionally, the version displayed on sidequest did not get updated automatically. I've fixed this, as well. (This is why you thought you needed to reinstall - you did not.)

**You may still be able to restore your old backup by following these steps:**
1. Update to 7.0.1 _(Otherwise your old backup will be overridden!)_
2. Make a backup of your 7.0.1 settings and groupings, which will not overwrite your old backup
3. Uninstall LL 7.0.1 
4. Install LL 6.3.X from releases
6. Import your old backup on 6.3.X; this should hopefully work as expected
7. Update from 6.3.X to 7.0.X, your settings will be migrated
(If that doesn't work, you can re-import the backup from step 1)

Hope that works. As the issues that led you to make this error are now resolved, I'm going to close this issue.

**Comment by johnnyb2012** [comment]
Actually I got 6.3 with my grouping and right settings, but on update
prompt 6.3.0 to 7.0.1
(download) it shows dialog window "Open with.."  e. g. Package installer or
"Use a different app".
When select Package installer, nothing happens and it shows again "An
update is vailable!" in loop.
So I do not know how to update. (Update via SideQuest resets the setting
and the old one is not importable).
J.B.
