### ISSUE TITLE
[Feature Request] Allow multiple apps to be opened in custom windows

### ISSUE THREAD

**Issue by Tadashi-Hikari** [threethan/LightningLauncher#116]
When an app is set to have a custom ratio, the app is launched as part of Lightning launcher. This prevents opening up multiple apps w/ lightning, as they will replace the currently launched app only allowing for a single application to be shown at a time

**Comment by threethan** [comment]
You can work around this by either launching apps as their own windows, or by launching apps from  separate Lightning Launcher "instances" similar to how you would multitask the launcher itself.
For example:
- Open LL via. feed shortcut, open app in custom window
- Drag custom window to the left
- Open LL via. people shortcut, open app in custom window
- There are now two custom windows

This previously worked a little nicer, but is like this now due to OS limitations. Since this is an already niche feature, I do not plan to find a more specialized workaround.
