### ISSUE TITLE
Customize Appearance

### ISSUE THREAD

**Issue by niktn10** [threethan/LightningLauncher#12]
Does not work, when you try to open the whole application crashes.
LightningLauncher 3.5
Quest V56

Besides:
Game title fonts are now black and unreadable on a dark background.
Application icons are not loaded and remain rectangular in square frames with margins.

**Comment by JarJarBlinkz** [comment]
same issue crashes whole app when trying to customize 
Quest V57 PTC

**Comment by threethan** [comment]
Will to some testing. The latest version was tested on the V57 PTC.

You can now change the text color between dark and light (previously, light text would be unreadable on dark backgrounds) but it needs to be manually set when updating or changing wallpapers.

Unsure about the app icons, though. Could someone check what happens when the application is uninstalled, removing all configuration data, then given a fresh install on the latest version? I suspect the icon cache may need to be cleared.

As to the crash, I have no idea what might be causing this. I'll perform some more testing on my end. Specific steps to reproduce would be greatly appreciated.

**Comment by daxxio** [comment]
Just did some testing, cleared appdata and removed LL 3.0.1. Then I installed 3.5. Problem is still there.
Steps to reproduce:
1) Install LL version from Rookie Sideloader.
2) Upgrade by using "Sideload APK" to install latest version of LL
3) Launch LL and try to Customize Appearance > Crash

**Comment by threethan** [comment]
This should be fixed in 4.0
