### ISSUE TITLE
keeps crashing on oculus go.

### ISSUE THREAD

**Issue by konstantine6** [threethan/LightningLauncher#26]
I downloaded this from sidequest to use on my go but it keeps crashing. it says in the description that it should work for all android devices

**Comment by threethan** [comment]
Hm, any idea how and when it crashes? 
I said that because I've tested on all the android devices I have + various emulator versions, but I don't have an oculus go to test on

**Comment by threethan** [comment]
I've fixed a crash that could sometimes occur continuously after the app was killed, as well as a few potential race conditions. I'm going to assume this issue is fixed, but will reopen if it's still occurs and would greatly appreciate more info.

The Quest OS has a lot of unexpected behaviours, so I wouldn't be surprised if some other strange behaviour existed on their earier products.
