### ISSUE TITLE
Quest custom icon issue

### ISSUE THREAD

**Issue by HoriZonUK** [threethan/LightningLauncher#27]
For Quest 2 and 3 when you edit or add an uploaded custom image of the icon it resets all of them to default also unhides all hidden apps as well. 

Have to re add all my images and hide 30 apps again. 

Latest public firmware for each device. 

Kinda annoying. Orherwise great app.

**Comment by threethan** [comment]
That seems pretty major! 
I'm not entirely sure what you mean by: "when you edit or add an uploaded custom image"
Do you mean setting a custom image for an app?
Did this happen once or is it a recurring issue?

I'd appreciate further clarification.

**Comment by HoriZon-nureekdotcom** [comment]
Yeah happens when editing a custom image for an app.

**Comment by threethan** [comment]
I'm not able to replicate this issue on my device.
Could you try a clean install?

1. (Recommended) Go to settings, then click `export configuration` to make a full backup
2. Open `Unknown Sources` in the Quest's launcher, hover LightiningLauncher, click the three dot button, then `Uninstall`
3. Re-Install LightningLauncher through your preferred method. Ensure you are using the latest version from GitHub or SideQuest. 
4. Let me know if the issue is still present on the clean install!
5. (Optional) If not, go to settings, then click `import configuration` to restore your settings.

**Comment by threethan** [comment]
Also btw your website has been compromised, you might wanna fix that or remove the link from your profile

**Comment by HoriZon-nureekdotcom** [comment]
Yeah did it on my Q2 and Q3 seems a bit better after the last few updates.

 But it happens when you edit a thumbnail and try to add a different one it would reset all the other and unhide all the hidden apps.


oh god i used to have that domain ill remove that now.

**Comment by threethan** [comment]
Still having trouble replicating it on my Quest 2, I'm afraid.

Can you confirm if:
- It happens on a clean install without restoring settings
- It resets settings other than hiding
- It happens with any consistency (maybe with only certain images or settings?) or if it just happens randomly when setting images

**Comment by HoriZonUK** [comment]
Ok did a video of it happening though it no longer reset other custom images 


One thing I did try before o did it I exported the cfg reloaded it and it seems to hide them all again.

**Comment by threethan** [comment]
Can you please try to replicate on a clean install? The video you sent is not a clean install.
I suspect this is caused by some form of data corruption. Without more information I can't fix this.

**Comment by HoriZonUK** [comment]
It was a clean install as it did it on my Q2 this is my Q3. All reinstalled from screech a week before.
