### ISSUE TITLE
Crashed heaset

### ISSUE THREAD

**Issue by lunchanddinner** [threethan/LightningLauncher#32]
Not sure if this is entirely Lightning's fault, but when I launched Lightning, then opened Quest browser, my headset completely crashed.

**Comment by threethan** [comment]
Could you elaborate on what you mean by 'completely crashed'?

Did it:
- Go black and mostly or completely unresponsive to inputs
- Display an error of some sort
- Reboot or shutdown
- Freeze or lock up while still displaying an image

If it's the first one specifically, it might have something to do with the launcher. If it's any of the others, it most likely doesn't.
If you can provide more detail or - ideally, steps to replicate - I will reopen and look into this further.

**Comment by lunchanddinner** [comment]
Sure, it just completely froze & shut down the headset, without even showing the Meta shut off logo. This got me a little freaked out as my headset wouldn't turn on again. Waited for an hour before turning on the headset again.

I would like to replicate it too but am very worried about bricking my quest. The exact steps I did were:

- Launch Lightning
- Clicked on Quest Browser within Lightning
- Headset crashed and shut down

**Comment by threethan** [comment]
Did you try long-pressing the power button to hard shut down?

If the device actually turned OFF, then the launcher had nothing to do with
it. If you were low on battery it may have been some sort of battery wear.

If the device stayed on but displayed a black screen and became
unresponsive, then it may have been caused by an app being launched
incorrectly. This can happen if another 2D app is launched while LL is
closing, or if LL somehow fails to close itself.

That issue will not harm your device, but you may have to hard power off
the headset (hold the power button for about 10 seconds then) then turn it
on again, which is very annoying.

**Comment by lunchanddinner** [comment]
Yes the screen did go black and unresponsive, I tried clicking around but nothing happened. I would say about 20-30 seconds later it then turned off. No low battery or anything, on a new Quest 3. Just sharing my results

**Comment by threethan** [comment]
I think what happened was this:
1. Black screen occurs and softlocks the device (This is caused by VRShell crashing itself)
2. Device goes to sleep after 30 seconds (typical). You interpret this as turning off, as the device refuses to resume
3. You wait about an hour and the device shuts down due to lack of battery, exiting the softlocked state
4. You turn the device back on and its back to normal.

If you held the power button for about 10 seconds, the headset would actually have powered off. Then you would have been able to turn it back on without waiting.

While this issue will not and cannot damage your device, it's still pretty serious. I noticed that the browser does not currently open with the correct intent, which may be related. I'll fix that shortly.

**Comment by lunchanddinner** [comment]
I think you may be right, good luck with it!
