### ISSUE TITLE
Option to convert between banner and normal icon

### ISSUE THREAD

**Issue by Risu** [threethan/LightningLauncher#37]
(Thanks for the udpates. You've brought this launcher to the next level.)
In version 6.1 my MX Player from android is displayed as a banner, but MPV from android is an icon. 
I would like an option to convert the MX Player banner to the icon to match.

**Comment by threethan** [comment]
The issue was that MX Player was being detected as a virtual reality app. I've updated app detection to fix this.
All unity apps are still detected as VR apps but that's such a minor issue idrc. If it was auto-categorized with VR apps, you'll still need to move it manually, but it will no longer display as a banner unless phone apps are set to display as banners.

**Comment by threethan** [comment]
Feel free to make a feature request for per-app banner display mode, but it's not currently planned.
