### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by joebobbio** [threethan/LightningLauncher#56]
Hi,
I've been using Lightning Launcher on my Android TV for a while now, but every update past 6.1.1 fails to install with the message `INSTALL_FAILED_NO_MATCHING_ABIS`. 
I assume this is due to the recent implementation of GeckoView - if so, could there be a possibility of official builds w/o it for better Android TV support?

**Comment by threethan** [comment]
It's not due to GeckoView - geckoview works fine on 32 bit. However, I opted to build for arm64 only as every additional ABI adds around 100 extra mb to the download. I may add a separate build if interest is there. Building for more platforms is easy, but getting the updater to properly decide without needing to make separate branches might be difficult. 32 bit builds would most likely have the updater disabled or non-functional, just to make my life easier.

 In the meantime, feel free to use 6.1 or build from source.
