### ISSUE TITLE
Wallpaper image sometimes does not appear

### ISSUE THREAD

**Issue by curvatura99** [threethan/LightningLauncher#57]
Let me first say that your application is fantastic and works great.  However there's one minor problem. When you minimize the launcher or exit sometimes the user defined wallpaper goes missing and instead you get a gray background. You have to go into settings and click one of the predefined wallpapers and then click the plus button to get it back. It's not a show stopper, but it can get a little annoying going back and forth.

**Comment by threethan** [comment]
I would like to note that this isn't actually specific to the custom wallpaper option - I believe it also happens with the built in wallpapers. This is caused by wallpapers somehow failing to load or be set. If this happens, the background is the wallpaper _color_, which is defined for all built-in wallpapers, but defaults to grey otherwise.

I've known about this issue for a while but it's not been a priority.

**Comment by threethan** [comment]
This should now be fixed and will be pushed with the next update.
