### ISSUE TITLE
Almost there.

### ISSUE THREAD

**Issue by ZAKsPop** [threethan/LightningLauncher#94]
OK. The last preview version is working nice. There was a couple weird things that it does but for the most part it is working well.
2 things I've experienced:
1: When changing an icon for a game, other games have different icons than what you have saved. But only for a few seconds.
![com oculus shellenv-20240107-185600](https://github.com/threethan/LightningLauncher/assets/62826396/9ae924e3-e0f4-4dae-ae2d-ac6184ae82ba)
![com oculus shellenv-20240107-185551](https://github.com/threethan/LightningLauncher/assets/62826396/b5dd9d39-c859-4fc9-98e8-572a80bf4ef5)

2: Some of the icons are very blurry even though they weren't always. Like a very low res icon is being used. Example: Pistol Whip
![com oculus shellenv-20240107-185455](https://github.com/threethan/LightningLauncher/assets/62826396/9aeba333-e538-441e-9dbd-f6b16f3b413d)

Other than those 2 things, it appears to be working fine. I'm going to continue using it instead of reverting back to the release version.

**Comment by threethan** [comment]
I've updated the release version to no longer clear the icon cache when setting a custom icon. Additionally, icon downloads will now be re-attempted whenever the launcher is reopened or groups are changed - which should clear up icon issues such as yours, which may be caused by inconsistent internet connectivity.
