### ISSUE TITLE
Multitasking + browser settings

### ISSUE THREAD

**Issue by ZeroUPS** [threethan/LightningLauncher#99]
The new multitasking features are really nice. I now have both facebook and monday shortcuts that open different lightning launcher windows. Is it possible to have an option for the people shortcut also be on click instead of hover ?
Also, is there a way to get 120 Hz for 2d android apps in lightning launcher ?
Another question : Lightning browser works well, but there is no settings menu, is one planned ? We can obviously use about:config for certain things but it's not as easy.
Thank you once again for this project

**Comment by threethan** [comment]
1. "Is it possible to have an option for the people shortcut also be on click instead of hover" - No
2. "Also, is there a way to get 120 Hz for 2d android apps in lightning launcher" - No
3. "Lightning browser works well, but there is no settings menu, is one planned ?" - No; If you have any options you think should be added, feel free to create a feature request issue in the Lightning Browser repository.
